### ISSUE TITLE
Connection Collector should not throw exceptions if closed

### ISSUE THREAD

**Issue by jbobnar** [diirt/diirt#57]
ConnectionCollector throws an exception if the collector is closed while the value is pending to be sent.
https://github.com/diirt/diirt/blob/master/pvmanager/datasource/src/main/java/org/diirt/datasource/ConnectionCollector.java#L45

This is a legitimate action. The client should be able to close the connection at any time, even if the first value from the PV has not yet arrived.
It is also dangerous, because the writeValue can be called from one of CAJ's threads. Throwing an exception on CAJ thread will kill its executor, requiring a restart of the whole application (see the stack trace below). 

java.lang.IllegalStateException: ConnectionCollector for
'UTIL-S15-AG07:HWC8-YT1' was closed.
    at
org.epics.pvmanager.ConnectionCollector$ConnectionWriteFunction.writeValue(ConnectionCollector.java:45)
    at
org.epics.pvmanager.ConnectionCollector$ConnectionWriteFunction.writeValue(ConnectionCollector.java:31)
    at
org.epics.pvmanager.MultiplexedChannelHandler$MonitorHandler.processConnection(MultiplexedChannelHandler.java:67)
    at
org.epics.pvmanager.MultiplexedChannelHandler.reportConnectionStatus(MultiplexedChannelHandler.java:123)
    at
org.epics.pvmanager.MultiplexedChannelHandler.setConnected(MultiplexedChannelHandler.java:364)
    at
org.epics.pvmanager.MultiplexedChannelHandler.processConnection(MultiplexedChannelHandler.java:163)
    at
org.epics.pvmanager.jca.JCAChannelHandler.access$600(JCAChannelHandler.java:51)
    at
org.epics.pvmanager.jca.JCAChannelHandler$3.connectionChanged(JCAChannelHandler.java:423)
    at
gov.aps.jca.event.DirectEventDispatcher.dispatch(DirectEventDispatcher.java:56)
    at com.cosylab.epics.caj.CAJChannel.setConnectionState(CAJChannel.java:643)
    at
com.cosylab.epics.caj.CAJChannel.connectionCompleted(CAJChannel.java:353)
    at
com.cosylab.epics.caj.impl.handlers.CreateChannelResponse.internalHandleResponse(CreateChannelResponse.java:48)
    at
com.cosylab.epics.caj.impl.handlers.AbstractCAResponseHandler.handleResponse(AbstractCAResponseHandler.java:110)
    at
com.cosylab.epics.caj.impl.CAResponseHandler.handleResponse(CAResponseHandler.java:139)
    at com.cosylab.epics.caj.impl.CATransport.processRead(CATransport.java:509)
    at com.cosylab.epics.caj.impl.CATransport.processRead(CATransport.java:421)
    at com.cosylab.epics.caj.impl.CATransport.handleEvent(CATransport.java:359)
    at
com.cosylab.epics.caj.impl.reactor.lf.LeaderFollowersHandler.handleEvent(LeaderFollowersHandler.java:77)
    at
com.cosylab.epics.caj.impl.reactor.Reactor.processInternal(Reactor.java:400)
    at com.cosylab.epics.caj.impl.reactor.Reactor.process(Reactor.java:284)
    at
com.cosylab.epics.caj.impl.reactor.lf.LeaderFollowersHandler.run(LeaderFollowersHandler.java:91)
    at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by jbobnar** [comment]
> It is also dangerous, because the writeValue can be called from one of CAJ's threads. Throwing an exception on CAJ thread will kill its executor, requiring a restart of the whole application (see the stack trace below). 

I see now that exception is eventually caught, but any further updates from caj are blocked. I am waiting to get a recipe for reproducing this.
