### ISSUE TITLE
Intermittent test failure org.diirt.datasource.sim.ErrorHandlingTest.exceptionInFunction

### ISSUE THREAD

**Issue by willrogers** [diirt/diirt#71]
```
Error Message

Didn't receive notifications

Stacktrace

java.lang.AssertionError: Didn't receive notifications
	at org.junit.Assert.fail(Assert.java:93)
	at org.diirt.datasource.sim.ErrorHandlingTest.exceptionInFunction(ErrorHandlingTest.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

**Comment by shroffk** [comment]
@willrogers Does increasing the sleep help? I did not have much luck reproducing it

[diirt-sim-datasource-test.zip](https://github.com/diirt/diirt/files/493489/diirt-sim-datasource-test.zip)

diff --git a/pvmanager/datasource-sim/src/test/java/org/diirt/datasource/sim/ErrorHandlingTest.java b/pvmanager/datasource-sim/src/test/java/org/diirt/datasource/sim/ErrorHandlingTest.java
index 9e470a1..520659e 100644
--- a/pvmanager/datasource-sim/src/test/java/org/diirt/datasource/sim/ErrorHandlingTest.java
+++ b/pvmanager/datasource-sim/src/test/java/org/diirt/datasource/sim/ErrorHandlingTest.java
@@ -84,7 +84,7 @@
                 .maxRate(TimeDuration.ofHertz(10));
         notificationReceived = false;
 
-        Thread.sleep(1000);
+        Thread.sleep(2000);
         pv.close();
         if (notificationReceived == false) {
             fail("Didn't receive notifications");

**Comment by willrogers** [comment]
We got the failure on Jenkins.  If I run it in my IDE it passes reliably.  

I ran some tests:

* Reduce the sleep to 1ms: failed 5 times out of 10
* Reduce the sleep to 100ms: failed 1 time out of 10
* Leave sleep at 1000ms: failed 0 times out of 10

The Jenkins build has run three times since then without failing.

Conclusion: something held that thread up by 1 second on that one run.  We can't put 10 second sleeps everywhere just in case.  So I'll close this.

**Comment by shroffk** [comment]
I dislike randomly setting up waits too...which is why the previous issue we resolved it by actually addressing the replay behaviour. I would like to do the same with this too and just wanted to better understand the Issue...I will keep you updated on this, could we keep this ticket open in the meanwhile.

**Comment by willrogers** [comment]
OK sure
