### ISSUE TITLE
Help with tests

### ISSUE THREAD

**Issue by claudio-rosati** [diirt/diirt#72]
Hello,

I’ve enabled Unit test on my local build pipeline and DIIRT failed math this point:
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.diirt.support.ca.DataUtilsTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.051 sec
Running org.diirt.support.ca.JCAChannelHandlerTest
Tests run: 16, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.127 sec
Running org.diirt.support.ca.JCADataSourceConfigurationTest
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.154 sec <<< FAILURE!
readDefaultConfiguration(org.diirt.support.ca.JCADataSourceConfigurationTest)  Time elapsed: 0.119 sec  <<< FAILURE!
java.lang.AssertionError:
Expected: ""
     got: "localhost"

	at org.junit.Assert.assertThat(Assert.java:780)
	at org.junit.Assert.assertThat(Assert.java:738)
	at org.diirt.support.ca.JCADataSourceConfigurationTest.readDefaultConfiguration(JCADataSourceConfigurationTest.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running org.diirt.support.ca.JCARTYPTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.036 sec
Running org.diirt.support.ca.JCAVTypeAdapterSetTest
Tests run: 70, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.157 sec
Running org.diirt.support.ca.JCAZeroPrecisionTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec

Results :

Failed tests:   readDefaultConfiguration(org.diirt.support.ca.JCADataSourceConfigurationTest): (..)

Tests run: 101, Failures: 1, Errors: 0, Skipped: 0
```
Is there something I missed?

Best regards,
Claudio

**Comment by shroffk** [comment]
what does your deafault cs.default.xml file look like
src/main/resources/org/diirt/support/ca/ca.default.xml
are there any changes there?

are there any caj/jca properties that you are setting as jvm properties?

**Comment by shroffk** [comment]
can you verify if the environment variable "EPICS_CA_ADDR_LIST" is set...

**Comment by claudio-rosati** [comment]
Hello Kunal,

no EPICS_CA_ADDR_LIST environment variable is set, and the src/main/resources/org/diirt/support/ca/ca.default.xml is the one coming from GitHub, with all content commented out (file attached).

[ca.default.xml.zip](https://github.com/diirt/diirt/files/502903/ca.default.xml.zip)

**Comment by claudio-rosati** [comment]
We have the presence of a `.JCALibrary` folder in my home directory containing the following `JCALibrary.properties` file:
```
com.cosylab.epics.caj.CAJContext.auto_addr_list=false
com.cosylab.epics.caj.CAJContext.addr_list=localhost
```
Removing it solved the problem.

**Comment by shroffk** [comment]
Well I don't think this is a behavior change...looking at the caj/jca code I did not find any new reference to the creation of this settings folders.
The properties files in the the jca and the caj libraries continue to use an empty string for the addr_list

**Comment by claudio-rosati** [comment]
No, it isn't a behavior change.
I think that when I run my previous examples with EPICS 3/4 this file was created (I don't remember to have done it myself, but it could be possible).

**Comment by berryma4** [comment]
There was a change in caj.  I had services, and cs-studio, where I had to go from localhost to null.

**Comment by berryma4** [comment]
Sorry to hijack the ticket, but here is the loopback add:
https://sourceforge.net/p/epics-jca/caj/ci/0132f0aa6129652ce1d0058b9be048b431630b49/tree/src/com/cosylab/epics/caj/util/nif/InetAddressUtilV6.java?diff=f0a69280446f9212c63f36b80488a6f90ab8391a

**Comment by shroffk** [comment]
So I think the commit only affects the socket creation when there is no address_list set.
Once Caludio delete the properties files, I don't think they were recreated...even when the rest of the tests were run...maybe we need more exhaustive tests which open and close the sockets used by caj.
For the time being I am not really sure if the commit you pointed to maps to the above failure...

**Comment by berryma4** [comment]
No it doesn't have anything to do with this ticket.  As I mentioned, I hijacked the thread, and I'm sorry.  I noticed the ```com.cosylab.epics.caj.CAJContext.addr_list=localhost``` and it reminded me of the issue I had.

**Comment by shroffk** [comment]
Ah...Ok then...
Your annoyance at changes being made without appropriate notification has been duly noted and you have been credited 23.53 patience and good guy points.

**Comment by willrogers** [comment]
23.53 is generous in my opinion.
