### ISSUE TITLE
Services >> JDBC - no suitable driver found for jdbc://postgresql.

### ISSUE THREAD

**Issue by boryto** [diirt/diirt#88]
When executing services deployed in $diirtconfigroot/services/jdbc which use the postgres database, we get 

java.sql.SQLException: No suitable driver found for
jdbc:postgresql://localhost/.....
    at java.sql.DriverManager.getConnection(DriverManager.java:689)
    at java.sql.DriverManager.getConnection(DriverManager.java:270)

This is due to the class-loading differences between SPI and OSGI. 
https://github.com/ControlSystemStudio/cs-studio/wiki/OSGi-and-ServiceLoaders

**Comment by boryto** [comment]
This issue is fixed by registering service to the OSGI service Registry.
A new maven profile "postgres" was created in pvmanager/service-jdbc/pom.xml that adds required tags to the MANIFEST file, so that service is registered to OSGI and postgres bundle dependency is added. 

Dependencies to [Apache Aries SPI fly](http://aries.apache.org/modules/spi-fly.html)  and postgres bundle must added to the product to satisfy profile requirements. 

Pull req #88
